[project]
name = "TWPA-TWPC-Simulator"
version = "0.1.0"
requires-python = ">=3.10"
description = ""

[project.dependencies]
numpy = ">=1.24"
matplotlib = ">=3.7"
scipy = ">=1.10"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = ["sympy", "sympy.*"]
ignore_missing_imports = true